application: ost-qna
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: QAPlatform.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
